### ISSUE TITLE
没有Runs.py

### ISSUE THREAD

**Issue by Castle0fGlass** [LibraryBooking/Booking#2]
同学你好，在文件里没有此运行文件，可否交流一下？

**Comment by LibraryBooking** [comment]
我之前好像是因为总体文件太大了分批上传的，可能有些文件没传到上面去




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Saturday, Sep 3, 2022 9:30 AM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[LibraryBooking/Booking] 没有Runs.py (Issue #2)





 
同学你好，在文件里没有此运行文件，可否交流一下？
 ***@***.***

**Comment by Castle0fGlass** [comment]
可以加一下联系方式嘛~ 我有几个问题想请教一下 : )

**Comment by LibraryBooking** [comment]
按你的邮箱的QQ发过去好友申请了
